# Generated by Django 5.1.5 on 2025-01-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.CharField(choices=[('E&t', 'Engineering AND Technology'), ('I&C', 'Informatic AND Computing'), ('Sc', 'Science'), ('MAGT', 'Management'), ('MS', 'Media Studies'), ('LS', 'Life Sciences'), ('IS', 'Intrdisciplinary Studies'), ('CCSD', 'Community College for Skill Development'), ('OTHER', 'Others')], default='OTHER', max_length=10),
        ),
    ]
