# Generated by Django 5.1.5 on 2025-01-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_department_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.CharField(choices=[('E&t', 'Engineering & Technology'), ('I&C', 'Informatic & Computing'), ('Sc', 'Science'), ('MAGT', 'Management Studies'), ('LMS', 'Languages & Media Studies'), ('LS', 'Life Sciences'), ('IS', 'Intrdisciplinary Studies'), ('CCSD', 'Community College for Skill Development'), ('OTHER', 'Others')], default='OTHER', max_length=10),
        ),
    ]
