# Generated by Django 5.1.5 on 2025-01-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_department_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('level', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('PhD', 'Doctoral'), ('PGD', 'Post Graduate Diploma'), ('DIP', 'Diploma'), ('CRT', 'Certificate'), ('Other', 'Other')], default='UG', max_length=6)),
                ('intake', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
