# Generated by Django 5.1.5 on 2025-01-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')]),
        ),
    ]
