# Generated by Django 5.1.5 on 2025-01-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_programsemester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('credit', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')])),
                ('nature', models.CharField(choices=[('Theory', 'Theory'), ('Lab', 'Lab'), ('Project', 'Project'), ('Seminar', 'Seminar'), ('Workshop', 'Workshop'), ('Training', 'Training'), ('Other', 'Other')], default='Theory', max_length=8)),
                ('type', models.CharField(choices=[('DS', 'Dicipline Specific'), ('AEC', 'Ability Enhancement Course'), ('VAC', 'Value Added Course'), ('Elective', 'Value Added Course'), ('Other', 'Other')], default='DS', max_length=12)),
                ('program_semesters', models.ManyToManyField(blank=True, related_name='subjects', to='academic.programsemester')),
            ],
        ),
    ]
