# Generated by Django 5.1.5 on 2025-01-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_syllabus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabus',
            old_name='subject',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='upload_syllabus',
            field=models.FileField(upload_to='syllabi/'),
        ),
    ]
